default: &default
  adapter: postgresql # postgresql database server
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 50000
  username: mohiuddin
  # password: nhyxp954648

development:
  <<: *default
  database: flix_development_07

test:
  <<: *default
  database: flix_test_07

production:
  <<: *default
  database: flix_production_07
